apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: quay.io/lightside/jenkins-jnlp-agent:0.1.0
    args: ['\$(JENKINS_SECRET)', '\$(JENKINS_NAME)']
  - name: docker
    image: docker:stable-dind
    command: ['cat']
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
