apiVersion: v1
kind: Pod
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: jnlp
    image: quay.io/lightside/jenkins-jnlp-agent:0.1.0
    tty: true
    securityContext:
      runAsUser: 10000
      allowPrivilegeEscalation: false
  - name: docker
    image: quay.io/lightside/jet:0.1.0
    tty: true
    volumeMounts:
    - name: dockersock
      mountPath: /var/run/docker.sock
    securityContext:
      runAsUser: 0
      privileged: true
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
